data_path: /path/to/generated
pair_set: /path/to/imagenet
save_best: false
image_size: 256
vq_model: VQ-16
enc_type: dinov2
dec_type: dinov2
semantic_guide: dinov2
global_batch_size: 1024
epochs: 100
finetune: true
lr_scheduler: cosine
lr: 5e-5
disc_lr: 5e-5
#max_grad_norm: 1.0
#reconstruction_weight: 4.0
codebook_embed_dim: 64
codebook_size: 4096
abs_pos_embed: true
product_quant: 1
ema: true
codebook_drop: 0.0
encoder_model: vit_base_patch14_dinov2.lvd142m
decoder_model: vit_base_patch14_dinov2.lvd142m
num_latent_tokens: 256
v_patch_nums: [16]
half_sem: false
guide_type_1: class
start_drop: 3
ckpt_every: 10000
sem_loss_weight: 0.1
enc_tuning_method: frozen
lecam_loss_weight: 0.001
weight_decay: 0.0
disc_weight_decay: 0.0005
disc_epoch_start: 0
disc_type: dinodisc
aug_fade_steps: 0
disc_adaptive_weight: true
anneal_start: 100
anneal_end: 100
alpha: 1.0
beta: 0.0
delta: 100
vis_every: 100
cloud_save_path: RobustTokp
vq_ckpt: RobustTok-half.pt
debug_disc: true